<?php

/**
 * Created by IntelliJ IDEA.
 * User: maxsky
 * Date: 2024 Sep 18
 * Time: 10:33
 */

namespace Tests\Connection;

use AMQPConnection;
use MaxSky\AMQP\Config\AMQPBaseConnection;
use MaxSky\AMQP\Config\AMQPConfig;
use MaxSky\AMQP\Exception\AMQPConnectionException;
use PhpAmqpLib\Connection\AbstractConnection;
use Tests\TestCase;

class TestConnectServer extends TestCase {

    /** @var AMQPConfig */
    private $config;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->config = new AMQPConfig();

        $this->config->connection_name = 'phpunit-test';

        $this->config->host = 'localhost';
        $this->config->port = 5672;
        $this->config->user = 'guest';
        $this->config->password = 'guest';
        $this->config->vhost = '/';

        $this->config->connect_options = [];
    }

    public function testConnectThroughExtension() {
        if (!extension_loaded('amqp')) {
            $this->fail('AMQP Extension not loaded.');
        }

        try {
            $baseConnection = new AMQPBaseConnection($this->config);

            $this->assertInstanceOf(AMQPConnection::class, $baseConnection->getConnection());
        } catch (AMQPConnectionException $e) {
            $this->fail($e->getMessage());
        }
    }

    public function testConnectThoughLibrary() {
        try {
            $baseConnection = new AMQPBaseConnection($this->config);

            $this->assertInstanceOf(AbstractConnection::class, $baseConnection->getConnection());
        } catch (AMQPConnectionException $e) {
            $this->fail($e->getMessage());
        }
    }
}
