<?php

/**
 * Created by IntelliJ IDEA.
 * User: maxsky
 * Date: 2024 Sep 18
 * Time: 10:28
 */

namespace Tests\Message;

use MaxSky\AMQP\Config\AMQPBaseConfig;
use MaxSky\AMQP\Config\AMQPConfig;
use MaxSky\AMQP\Exception\AMQPConnectionException;
use MaxSky\AMQP\Exception\AMQPQueueException;
use MaxSky\AMQP\Message;
use Tests\TestCase;

class TestSendMessage extends TestCase {

    /** @var AMQPConfig */
    private $config;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $config = new AMQPBaseConfig();

        $config->connection_name = 'phpunit-test';

        $config->host = 'localhost';
        $config->port = 5672;
        $config->user = 'guest';
        $config->password = 'guest';
        $config->vhost = '/';

        $config->connect_options = [];

        $this->config = new AMQPConfig($config);
    }

    /**
     * @return void
     * @throws AMQPConnectionException
     * @throws AMQPQueueException
     * @throws \AMQPConnectionException
     */
    public function testSend() {
        Message::init($this->config)->send(ExampleMessageHandler::class, [
            'name' => 'phpunit-test',
            'message' => 'hello world',
            'create_time' => time()
        ], 'phpunit-queue');
    }
}
