<?php

/**
 * Created by IntelliJ IDEA.
 * User: maxsky
 * Date: 2024 Sep 18
 * Time: 10:28
 */

namespace Tests\Message;

use MaxSky\AMQP\Config\AMQPBaseConfig;
use Tests\TestCase;

class TestReceiveMessage extends TestCase {

    private $config;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->config = new AMQPBaseConfig();

        $this->config->connection_name = 'phpunit-test';

        $this->config->host = '127.0.0.1';
        $this->config->port = 5672;
        $this->config->user = 'guest';
        $this->config->password = 'guest';
        $this->config->vhost = '/';
    }
}
