<?php

/**
 * Created by IntelliJ IDEA.
 * User: maxsky
 * Date: 2024 Sep 18
 * Time: 10:28
 */

namespace Tests\Message;

use Carbon\Carbon;
use MaxSky\AMQP\Config\AMQPConfig;
use MaxSky\AMQP\Exception\AMQPConnectionException;
use MaxSky\AMQP\Exception\AMQPQueueException;
use MaxSky\AMQP\Message;
use Tests\TestCase;

class TestSendMessage extends TestCase {

    /** @var AMQPConfig */
    private $config;

    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->config = new AMQPConfig();

        $this->config->connection_name = 'phpunit-test';

        $this->config->host = 'localhost';
        $this->config->port = 5672;
        $this->config->user = 'guest';
        $this->config->password = 'guest';
        $this->config->vhost = '/';

        $this->config->connect_options = [];
    }

    /**
     * @return void
     * @throws AMQPConnectionException
     * @throws AMQPQueueException
     */
    public function testSend() {
        Message::init($this->config)->send(ExampleMessageHandler::class, [
            'name' => 'phpunit-test',
            'message' => 'hello world',
            'create_time' => Carbon::now()->timestamp
        ], 'phpunit-queue');
    }
}
